server:
  port: 8080
spring:
  application:
    name: config-server2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangxiechen/cloud_demo.git
          search-paths: config-repo